/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecalculoInsumosRouteImport } from './routes/recalculo-insumos'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersCreateRouteImport } from './routes/users/create'
import { Route as PartidasVinculacionRouteImport } from './routes/partidas/vinculacion'
import { Route as PartidasClonacionRouteImport } from './routes/partidas/clonacion'
import { Route as DivisasDiscrepanciasRouteImport } from './routes/divisas/discrepancias'

const RecalculoInsumosRoute = RecalculoInsumosRouteImport.update({
  id: '/recalculo-insumos',
  path: '/recalculo-insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasVinculacionRoute = PartidasVinculacionRouteImport.update({
  id: '/partidas/vinculacion',
  path: '/partidas/vinculacion',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasClonacionRoute = PartidasClonacionRouteImport.update({
  id: '/partidas/clonacion',
  path: '/partidas/clonacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisasDiscrepanciasRoute = DivisasDiscrepanciasRouteImport.update({
  id: '/divisas/discrepancias',
  path: '/divisas/discrepancias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recalculo-insumos': typeof RecalculoInsumosRoute
  '/divisas/discrepancias': typeof DivisasDiscrepanciasRoute
  '/partidas/clonacion': typeof PartidasClonacionRoute
  '/partidas/vinculacion': typeof PartidasVinculacionRoute
  '/users/create': typeof UsersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recalculo-insumos': typeof RecalculoInsumosRoute
  '/divisas/discrepancias': typeof DivisasDiscrepanciasRoute
  '/partidas/clonacion': typeof PartidasClonacionRoute
  '/partidas/vinculacion': typeof PartidasVinculacionRoute
  '/users/create': typeof UsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recalculo-insumos': typeof RecalculoInsumosRoute
  '/divisas/discrepancias': typeof DivisasDiscrepanciasRoute
  '/partidas/clonacion': typeof PartidasClonacionRoute
  '/partidas/vinculacion': typeof PartidasVinculacionRoute
  '/users/create': typeof UsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/recalculo-insumos'
    | '/divisas/discrepancias'
    | '/partidas/clonacion'
    | '/partidas/vinculacion'
    | '/users/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/recalculo-insumos'
    | '/divisas/discrepancias'
    | '/partidas/clonacion'
    | '/partidas/vinculacion'
    | '/users/create'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/recalculo-insumos'
    | '/divisas/discrepancias'
    | '/partidas/clonacion'
    | '/partidas/vinculacion'
    | '/users/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RecalculoInsumosRoute: typeof RecalculoInsumosRoute
  DivisasDiscrepanciasRoute: typeof DivisasDiscrepanciasRoute
  PartidasClonacionRoute: typeof PartidasClonacionRoute
  PartidasVinculacionRoute: typeof PartidasVinculacionRoute
  UsersCreateRoute: typeof UsersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recalculo-insumos': {
      id: '/recalculo-insumos'
      path: '/recalculo-insumos'
      fullPath: '/recalculo-insumos'
      preLoaderRoute: typeof RecalculoInsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/vinculacion': {
      id: '/partidas/vinculacion'
      path: '/partidas/vinculacion'
      fullPath: '/partidas/vinculacion'
      preLoaderRoute: typeof PartidasVinculacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/clonacion': {
      id: '/partidas/clonacion'
      path: '/partidas/clonacion'
      fullPath: '/partidas/clonacion'
      preLoaderRoute: typeof PartidasClonacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisas/discrepancias': {
      id: '/divisas/discrepancias'
      path: '/divisas/discrepancias'
      fullPath: '/divisas/discrepancias'
      preLoaderRoute: typeof DivisasDiscrepanciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RecalculoInsumosRoute: RecalculoInsumosRoute,
  DivisasDiscrepanciasRoute: DivisasDiscrepanciasRoute,
  PartidasClonacionRoute: PartidasClonacionRoute,
  PartidasVinculacionRoute: PartidasVinculacionRoute,
  UsersCreateRoute: UsersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
